
function emoji(){
	for(var i = 0 ; i < document.body.all.length ; i++){
		var body=document.body.all(i)
 		replace(body,"BeforeBegin");
 		try{
 			if(body.tagName != "TEXTAREA" && body.tagName != "INPUT" && body.tagName != "OPTION" && body.tagName != "SUBMIT"){
 				replace(body,"AfterBegin");
			}
		}catch (e){}
	}
}
function replace(body,t){
	var str = body.getAdjacentText(t);
	var i = 0;
	var ch = 0;
	while(isFinite(cc = str.charCodeAt(i++))){
		
		if((cc >= 57345 && cc <= 59223) || (cc >= 63647 && cc <= 63996)){
			var sj = cc.toString(16);
			var hhh = change_sjis(sj);
			if (hhh) {
				str = str.slice(0,i-1)+(hhh)+str.slice(i);
			}
			ch ++;
		}
	}
	if(ch){
		body.replaceAdjacentText(t,"");
		body.insertAdjacentHTML(t,str);
	}
	if(t=="BeforeBegin")replace(body,"AfterEnd");
	else if(t=="AfterBegin")replace(body,"BeforeEnd");
}

function change_sjis(c){
	var code  = c;
	
	
	emoji['e481'] ='';//！                             D
	emoji['e482'] ='';//！                             D
	emoji['e483'] ='';//？
	emoji['e52c'] ='';//？
	emoji['e52d'] ='＜';//左向き三角１
	emoji['e52e'] ='＞';//右向き三角１
	emoji['e52f'] ='＜＜';//左向き三角２
	emoji['e530'] ='＞＞';//右向き三角２
	emoji['e531'] ='■';//小四角１
	emoji['e532'] ='■';//小四角２
	emoji['e533'] ='i';//インフォメーションシンボル
	emoji['e4c1'] ='';//ワイングラス                   D
	emoji['e511'] ='[スピーカ]';//スピーカ
	emoji['e579'] ='';//ドル                           D
	emoji['e486'] ='';//月１                           D
	emoji['e487'] ='';//いなずま                       D
	emoji['e534'] ='■';//中四角１
	emoji['e535'] ='■';//中四角２
	emoji['e536'] ='◆';//小菱形１
	emoji['e537'] ='◆';//小菱形２
	emoji['e538'] ='■';//大四角１
	emoji['e539'] ='■';//大四角１
	emoji['e53a'] ='●';//小丸１
	emoji['e53b'] ='●';//小丸2
	emoji['e57a'] ='';//腕時計                         D
	emoji['e53c'] ='＋';//プラス
	emoji['e53d'] ='－';//マイナス
	emoji['e53e'] ='＊';//星１
	emoji['e53f'] ='↑';//上矢印１
	emoji['e540'] ='↓';//下矢印１
	emoji['e541'] ='';//丸に斜め線
	emoji['e542'] ='▼';//下三角１
	emoji['e543'] ='▲';//上三角１
	emoji['e544'] ='▼';//下三角２
	emoji['e545'] ='▲';//上三角２
	emoji['e546'] ='◆';//大菱形１
	emoji['e547'] ='◆';//大菱形２
	emoji['e548'] ='■';//特大四角１
	emoji['e549'] ='■';//特大四角２
	emoji['e54a'] ='●';//大丸１
	emoji['e54b'] ='●';//大丸２
	emoji['e54c'] ='';//上矢印２
	emoji['e54d'] ='';//下矢印２
	emoji['e488'] ='';//太陽                           D
	emoji['e4ba'] ='';//野球ボール                     D
	emoji['e594'] ='';//時計                           D
	emoji['e489'] ='';//月２（顔つき）
	emoji['e512'] ='';//ベル                           D
	emoji['e560'] ='φ';//プッシュピン（画鋲）
	emoji['e4fa'] ='';//小顔
	emoji['e595'] ='';//ハート                         D
	emoji['e4c2'] ='';//マティーニ（カクテルグラス）   D
	emoji['e513'] ='';//四つ葉                         D
	emoji['e54e'] ='';//トレードマーク（TM）           D
	emoji['e54f'] ='×';//かける
	emoji['e561'] ='';//文書１                         D
	emoji['e57b'] ='';//砂時計１
	emoji['e47c'] ='';//砂時計２                       D
	emoji['e562'] ='';//フロッピーディスク１
	emoji['e48a'] ='';//雪の結晶
	emoji['e550'] ='×';//バツ１
	emoji['e551'] ='×';//バツ２
	emoji['e552'] ='→';//右矢印１
	emoji['e553'] ='←';//左矢印１ 
	emoji['e4c3'] ='';//マグカップ                     D
	emoji['e554'] ='÷';//割る
	emoji['e563'] ='';//カレンダー
	emoji['e4fb'] ='';//スマイルフェイス
	emoji['e48b'] ='★';//星２
	emoji['e555'] ='';//右矢印２                       D
	emoji['e556'] ='';//左矢印２                       D
	emoji['e514'] ='';//ジュエリー                     D
	emoji['e557'] ='';//チェックマーク１
	emoji['e4df'] ='';//犬（プードル）
	emoji['e468'] ='☆彡';//星３
	emoji['e46c'] ='';//スパーク
	emoji['e476'] ='';//電球                           D
	emoji['e4e0'] ='';//鳥                             D
	emoji['e58f'] ='';//フォルダ１（閉）
	emoji['e4fc'] ='';//顔１
	emoji['e558'] ='';//コピーライトマーク             D
	emoji['e559'] ='';//レジスタードマーク             D
	emoji['e49c'] ='';//ブリーフケース(ハンドバック）
	emoji['e590'] ='';//フォルダ２（開）
	emoji['e596'] ='';//電話１（プッシュホン）         D
	emoji['e4fd'] ='[ｺﾒﾝﾄ]';//吹き出しコメント
	emoji['e57c'] ='';//クレジットカード
	emoji['e55a'] ='▲';//上三角３
	emoji['e55b'] ='▼';//下三角３
	emoji['e573'] ='[USA]';//ＵＳＡ
	emoji['e49d'] ='';//ノート３
	emoji['e564'] ='';//クリップボード
	emoji['e597'] ='';//カップ                         D
	emoji['e515'] ='';//カメラ                         D
	emoji['e48c'] ='';//雨                             D
	emoji['e4bb'] ='[ｱﾒﾌﾄ]';//フットボール
	emoji['e565'] ='';//本１
	emoji['e484'] ='';//立ち入り禁止
	emoji['e46a'] ='';//信号                           D
	emoji['e566'] ='';//本２
	emoji['e567'] ='';//本３
	emoji['e568'] ='';//本４
	emoji['e569'] ='';//文書２
	emoji['e516'] ='';//はさみ                         D
	emoji['e56a'] ='';//ひめくりカレンダー
	emoji['e49e'] ='';//チケット・キップ               D
	emoji['e48d'] ='';//くもり                         D
	emoji['e521'] ='[封筒]';//封筒
	emoji['e57d'] ='';//小切手（CHECK）                D
	emoji['e517'] ='';//ビデオカメラ                   D
	emoji['e57e'] ='';//ハンディカム
	emoji['e4ab'] ='';//家                             D
	emoji['e4e4'] ='';//花                             D
	emoji['e57f'] ='';//ナイフ
	emoji['e580'] ='';//ビデオテープ
	emoji['e4fe'] ='';//めがね                         D
	emoji['e55c'] ='└→';//回り矢印１
	emoji['e55d'] ='';//回り矢印２                     D
	emoji['e518'] ='';//むしめがね                     D
	emoji['e519'] ='';//鍵                             D
	emoji['e56b'] ='';//ノート１
	emoji['e49f'] ='';//ノート２（開）                 D
	emoji['e581'] ='[ネジ]';//ボルト＆ナット
	emoji['e51a'] ='';//くつ                           D
	emoji['e4b1'] ='';//車                             D
	emoji['e582'] ='';//フロッピー２
	emoji['e574'] ='';//チャート（棒グラフ）
	emoji['e575'] ='';//グラフ１（折れ線グラフ）
	emoji['e51b'] ='';//メールボックス
	emoji['e583'] ='';//懐中電灯
	emoji['e56c'] ='';//Roldex
	emoji['e55e'] ='[ﾁｪｯｸ]';//チェックマーク２
	emoji['e4ce'] ='';//はっぱ                         D
	emoji['e4e1'] ='';//猟犬                           D
	emoji['e584'] ='[電池]';//電池
	emoji['e55f'] ='';//スクロール
	emoji['e56d'] ='φ';//がびょう
	emoji['e51c'] ='';//錠前
	emoji['e585'] ='';//ドル札
	emoji['e4ff'] ='←';//指差し確認左
	emoji['e500'] ='→';//指差し確認右
	emoji['e56e'] ='';//台帳
	emoji['e4a0'] ='';//クリップ                       D
	emoji['e4cf'] ='';//プレゼント                     D
	emoji['e51d'] ='';//名札
	emoji['e4ac'] ='';//ゴハン１                       D
	emoji['e56f'] ='';//複数本
	emoji['e4b2'] ='';//トラック
	emoji['e4a1'] ='';//エンピツ                       D
	emoji['e586'] ='[PDC]';//ロゴ（ＰＤＣ社）
	emoji['e591'] ='';//封筒２
	emoji['e587'] ='';//レンチ                         D
	emoji['e592'] ='';//送信ＢＯＸ
	emoji['e593'] ='';//受信ＢＯＸ
	emoji['e51e'] ='';//電話２
	emoji['e4ad'] ='';//工場・建物                     D
	emoji['e570'] ='[定規]';//定規１
	emoji['e4a2'] ='[定規]';//定規２
	emoji['e576'] ='';//グラフ２
	emoji['e4c4'] ='';//食事２
	emoji['e588'] ='';//電話３                         D
	emoji['e589'] ='[ｺﾝｾﾝﾄ]';//コンセント
	emoji['e501'] ='';//家族
	emoji['e58a'] ='';//リンク
	emoji['e51f'] ='';//パッケージ
	emoji['e520'] ='';//ＦＡＸ
	emoji['e48e'] ='';//ときどき曇り
	emoji['e4b3'] ='';//飛行機                         D
	emoji['e4b4'] ='';//ボート(船）                    D
	emoji['e4c8'] ='[ｻｲｺﾛ]';//サイコロ
	emoji['e58b'] ='';//新聞
	emoji['e4b5'] ='';//電車                           D
	emoji['e58c'] ='　';//全部ブランク
	emoji['e58d'] =' ';//半分ブランク
	emoji['e58e'] =' ';//4分の１ブランク
	emoji['e47d'] ='';//喫煙                           D
	emoji['e47e'] ='';//禁煙                           D
	emoji['e47f'] ='';//車椅子                         D
	emoji['e480'] ='';//若葉マーク
	emoji['e522'] ='';//四角数字１                     D
	emoji['e523'] ='';//四角数字2                      D
	emoji['e524'] ='';//四角数字3                      D
	emoji['e525'] ='';//四角数字4                      D
	emoji['e526'] ='';//四角数字5                      D
	emoji['e527'] ='';//四角数字6                      D
	emoji['e528'] ='';//四角数字7                      D
	emoji['e529'] ='';//四角数字8                      D
	emoji['e52a'] ='';//四角数字9                      D
	emoji['e52b'] ='';//四角数字10
	emoji['e469'] ='';//台風                           D
	emoji['e485'] ='';//ゆきだるま                     D
	emoji['e48f'] ='';//星座（おひつじ座）             D
	emoji['e490'] ='';//星座（おうし座）               D
	emoji['e491'] ='';//星座（双子座）                 D
	emoji['e492'] ='';//星座（かに座）                 D
	emoji['e493'] ='';//星座（しし座）                 D
	emoji['e494'] ='';//星座（おとめ座）               D
	emoji['e495'] ='';//星座（天秤座）                 D
	emoji['e496'] ='';//星座（さそり座）               D
	emoji['e497'] ='';//星座（いて座）                 D
	emoji['e498'] ='';//星座（やぎ座）                 D
	emoji['e499'] ='';//星座（水瓶座）                 D
	emoji['e49a'] ='';//星座（うお座）                 D
	emoji['e49b'] ='[星座]';//星座（へびつかい座）
	emoji['e4a3'] ='';//ＡＴＭ                         D
	emoji['e4a4'] ='';//２４HOURS（コンビニ)           D
	emoji['e4a5'] ='';//トイレ                         D
	emoji['e4a6'] ='';//パーキング                     D
	emoji['e4a7'] ='';//バス停
	emoji['e4a8'] ='';//ｱﾝﾃﾅ（位置情報ﾏｰｸ）
	emoji['e4a9'] ='';//港（いかりマーク）
	emoji['e4aa'] ='';//銀行                           D
	emoji['e571'] ='';//ガススタンド                   D
	emoji['e572'] ='[MAP]';//地図
	emoji['e4ae'] ='';//自転車                         D
	emoji['e4af'] ='';//バス                           D
	emoji['e4b0'] ='';//新幹線                         D
	emoji['e46b'] ='';//マラソン                       D
	emoji['e4b6'] ='';//サッカー                       D
	emoji['e4b7'] ='';//テニス                         D
	emoji['e4b8'] ='';//スノーボード                   D
	emoji['e4b9'] ='';//チェッカーフラグ（モータース   D
	emoji['e46d'] ='';//遊園地
	emoji['e4bc'] ='';//温泉                           D
	emoji['e4bd'] ='';//居酒屋（赤ちょうちん）
	emoji['e4be'] ='';//映画（かちんこ）               D
	emoji['e4bf'] ='';//夜の橋
	emoji['e4c0'] ='[東京ﾀﾜｰ]';//東京タワー
	emoji['e46e'] ='777';//スロット（７７７）
	emoji['e46f'] ='';//くす玉（アタリのくす玉）
	emoji['e4c5'] ='◎';//当選弓矢
	emoji['e4c6'] ='';//ゲームのコントローラ           D
	emoji['e4c7'] ='';//賞金                           D
	emoji['e4c9'] ='';//クリスマスツリー               D
	emoji['e4ca'] ='';//花見(さくら）                  D
	emoji['e4cb'] ='';//お化け
	emoji['e4cc'] ='';//旗（祝日・日の丸）
	emoji['e4cd'] ='';//スイカ
	emoji['e4d0'] ='';//ケーキ                         D
	emoji['e4d1'] ='';//フライパン（目玉焼き）
	emoji['e4d2'] ='';//さくらんぼ                     D
	emoji['e4d3'] ='';//ふぐ
	emoji['e4d4'] ='';//イチゴ
	emoji['e4d5'] ='';//おにぎり                       D
	emoji['e4d6'] ='';//ハンバーガー（ファーストフー   D
	emoji['e470'] ='';//くじら
	emoji['e4d7'] ='';//うさぎ
	emoji['e4d8'] ='';//うま                           D
	emoji['e4d9'] ='';//さる
	emoji['e4da'] ='';//かえる
	emoji['e4db'] ='';//猫                             D
	emoji['e4dc'] ='';//ペンギン                       D
	emoji['e4dd'] ='';//あり
	emoji['e4de'] ='';//ぶた                           D
	emoji['e4e2'] ='';//やしのき
	emoji['e4e3'] ='';//ひまわり
	emoji['e471'] ='';//顔１（うれしいカオ）           D
	emoji['e472'] ='';//顔２（おこったカオ）           D
	emoji['e473'] ='';//顔３（かなしいカオ）           D
	emoji['e474'] ='';//顔４（つかれたカオ）
	emoji['e475'] ='';//眠い（ＺＺＺ…）               D
	emoji['e4e5'] ='';//怒り（ムカッ）                 D
	emoji['e4e6'] ='';//雫（涙・汗）                   D
	emoji['e4e7'] ='';//からかう（あっかんべえ）       D
	emoji['e477'] ='';//ハート２（われている）         D
	emoji['e478'] ='';//ハート３（大きい＆小さい）     D
	emoji['e479'] ='';//スパーク２（キラリマーク）
	emoji['e47a'] ='';//爆弾                           D
	emoji['e47b'] ='[炎]';//炎
	emoji['e4e8'] ='';//捜索（SOS）
	emoji['e4e9'] ='';//力こぶ
	emoji['e4ea'] ='';//ハート５（矢がささっている）
	emoji['e4eb'] ='';//キスマーク                     D
	emoji['e4ec'] ='';//宇宙人
	emoji['e4ed'] ='';//なると
	emoji['e4ee'] ='';//足跡（犬）
	emoji['e4ef'] ='';//悪魔
	emoji['e4f0'] ='';//花丸
	emoji['e4f1'] ='';//丸秘                           D
	emoji['e4f2'] ='[100点]';//100点満点
	emoji['e4f3'] ='';//パンチ                         D
	emoji['e4f4'] ='';//ダッシュ                       D
	emoji['e4f5'] ='[ウンチ]';//ウンチマーク
	emoji['e4f6'] ='';//人差し指サイン
	emoji['e4f7'] ='[得]';//マル得
	emoji['e4f8'] ='';//どくろ
	emoji['e4f9'] ='';//おやゆびサイン                 D
	emoji['e502'] ='';//テレビ                         D
	emoji['e503'] ='';//マイク                         D
	emoji['e504'] ='';//財布                           D
	emoji['e505'] ='';//メロディ                       D
	emoji['e506'] ='';//ギター（エレキ）
	emoji['e507'] ='';//バイオリン（クラッシック）
	emoji['e508'] ='';//ヘッドフォン                   D
	emoji['e509'] ='';//口紅                           D
	emoji['e50a'] ='';//アクション（ピストル）
	emoji['e50b'] ='';//エステ
	emoji['e577'] ='[EZ]';//EZマーク
	emoji['e578'] ='';//無料（ＦＲＥＥ）               D
	emoji['e50c'] ='';//CD/DVD                         D
	emoji['e50d'] ='';//婦人服
	emoji['e50e'] ='';//UFO
	emoji['e50f'] ='';//更新（ＵＰ！）
	emoji['e510'] ='[注射]';//注射器（血）
	emoji['e598'] ='';//霧                             D
	emoji['e599'] ='';//ゴルフ                         D
	emoji['e59a'] ='';//バスケットボール               D
	emoji['e59b'] ='';//ポケットベル                   D
	emoji['e59c'] ='';//アート                         D
	emoji['e59d'] ='';//演劇
	emoji['e59e'] ='';//イベント                       D
	emoji['e59f'] ='';//リボン                         D
	emoji['e5a0'] ='';//バースデー                     D
	emoji['e5a1'] ='';//スペード                       D
	emoji['e5a2'] ='';//ダイヤ                         D
	emoji['e5a3'] ='';//クラブ                         D
	emoji['e5a4'] ='';//目                             D
	emoji['e5a5'] ='';//耳                             D
	emoji['e5a6'] ='';//手（チョキ）                   D
	emoji['e5a7'] ='';//手（パー）                     D
	emoji['e5a8'] ='';//新月                           D
	emoji['e5a9'] ='';//やや欠け月                     D
	emoji['e5aa'] ='';//半月                           D
	emoji['e5ab'] ='';//クリア                         D
	emoji['e5ac'] ='';//四角数字0                      D
	emoji['e5ad'] ='';//決定                           D
	emoji['e5ae'] ='';//ふらふら                       D
	emoji['e5af'] ='';//かわいい
	emoji['e5b0'] ='';//どんっ（衝撃）                 D
	emoji['e5b1'] ='';//あせあせ（飛び散る汗）         D
	emoji['e5b2'] ='[EZ]';//イージープラス
	emoji['e5b3'] ='';//地球
	emoji['e5b4'] ='';//ラーメン                       D
	emoji['e5c8'] ='';//NEW                            D
	emoji['e5c9'] ='';//紳士服                         D
	emoji['e5ca'] ='';//紳士靴
	emoji['e5cb'] ='';//パソコン                       D
	emoji['e5cc'] ='';//ラジオ
	emoji['e5cd'] ='';//バラ
	emoji['e5ce'] ='';//チャペル
	emoji['e5cf'] ='';//地下鉄                         D
	emoji['e5d0'] ='';//富士山                         D
	emoji['e5d1'] ='';//八分音符                       D
	emoji['e5d2'] ='';//天使
	emoji['e5d3'] ='';//トラ
	emoji['e5d4'] ='';//くま
	emoji['e5d5'] ='';//ねずみ
	emoji['e5d6'] ='';//ウインク                       D
	emoji['e5d7'] ='';//目がハート                     D
	emoji['e5d8'] ='';//ショッキング                   D
	emoji['e5d9'] ='';//困り                           D
	emoji['e5da'] ='';//たこ
	emoji['e5db'] ='[ﾛｹｯﾄ]';//ロケット
	emoji['e5dc'] ='';//王冠                           D
	emoji['e5dd'] ='';//チュー
	emoji['e5de'] ='';//ハンマー
	emoji['e5df'] ='';//打ち上げ花火
		emoji['e234'] ='';//枯れ葉
		emoji['e235'] ='';//仕事かばん
		emoji['e236'] ='';//噴水
		emoji['e237'] ='';//キャンプ
		emoji['e238'] ='[ﾏｰｼﾞｬﾝ]';//麻雀
		emoji['e239'] ='[VS]';//ＶＳ（バーサス）
		emoji['e23a'] ='';//トロフィー
		emoji['e23b'] ='';//カメ
		emoji['e23c'] ='';//スペイン国旗
		emoji['e23d'] ='';//ロシア国旗
		emoji['e23e'] ='';//工事中
		emoji['e23f'] ='';//風呂
		emoji['e240'] ='';//祝日マーク
		emoji['e241'] ='';//夕方街並み
		emoji['e242'] ='';//卵割り
		emoji['e243'] ='';//株価
		emoji['e244'] ='';//ポリス
		emoji['e245'] ='';//郵便局                         D
		emoji['e246'] ='';//病院                           D
		emoji['e247'] ='';//学校                           D
		emoji['e248'] ='';//ホテル                         D
		emoji['e249'] ='';//船                             D
		emoji['e24a'] ='';//18禁
		emoji['e24b'] ='';//圏内
		emoji['e24c'] ='';//COOL!
		emoji['e24d'] ='[割]';//割マーク
		emoji['e24e'] ='[サ]';//ザ・マーク
		emoji['e24f'] ='';//ＩＤマーク                     D
		emoji['e250'] ='';//満マーク                       D
		emoji['e251'] ='';//空マーク                       D
		emoji['e252'] ='[指]';//指定マーク
		emoji['e253'] ='[営]';//営業中マーク
		emoji['e254'] ='↑';//上指差し
		emoji['e255'] ='↓';//下指差し
		emoji['e256'] ='';//占い
		emoji['e257'] ='';//マナーモード
		emoji['e258'] ='OFF';//電源OFF
		emoji['e259'] ='';//メモする
		emoji['e25a'] ='[ﾈｸﾀｲ]';//ネクタイ
		emoji['e25b'] ='';//ハイビスカス
		emoji['e25c'] ='';//花束
		emoji['e25d'] ='';//サボテン
		emoji['e25e'] ='';//お銚子＆杯                     D
		emoji['e25f'] ='';//乾杯
		emoji['e260'] ='[祝]';//祝マーク
		emoji['e261'] ='';//風邪薬
		emoji['e262'] ='';//風船
		emoji['e263'] ='';//クラッカー
		emoji['e264'] ='[EZ]';//eznavigation
		emoji['e265'] ='';//帽子
		emoji['e266'] ='';//ロングブーツ
		emoji['e267'] ='';//ネイル
		emoji['e268'] ='';//美容院
		emoji['e269'] ='';//床屋
		emoji['e26a'] ='';//着物
		emoji['e26b'] ='';//ビキニ
		emoji['e26c'] ='';//ハート（トランプ）             D
		emoji['e26d'] ='';//光るハート
		emoji['e26e'] ='';//青ハート
		emoji['e26f'] ='';//緑ハート
		emoji['e270'] ='';//緑ハート
		emoji['e271'] ='';//紫ハート
		emoji['e272'] ='';//きらきら                       D
		emoji['e273'] ='';//スキー                         D
		emoji['e274'] ='';//○
		emoji['e275'] ='';//日本茶                         D
		emoji['e276'] ='';//食パン                         D
		emoji['e277'] ='';//ソフトクリーム
		emoji['e278'] ='';//ポテト
		emoji['e279'] ='';//だんご
		emoji['e27a'] ='';//おせんべい
		emoji['e27b'] ='';//ごはん
		emoji['e27c'] ='';//スパゲッティ
		emoji['e27d'] ='';//カレー
		emoji['e27e'] ='';//おでん
		emoji['e27f'] ='';//寿司
		emoji['e280'] ='';//りんご                         D
		emoji['e281'] ='';//みかん
		emoji['e282'] ='';//トマト
		emoji['e283'] ='';//なす
		emoji['e284'] ='';//弁当
		emoji['e285'] ='';//鍋
		emoji['e286'] ='';//ふっ                           D
		emoji['e287'] ='';//しょぼり                       D
		emoji['e288'] ='';//勝ち誇り
		emoji['e289'] ='';//失敗                           D
		emoji['e28a'] ='';//わからん                       D
		emoji['e28b'] ='';//眠い
		emoji['e28c'] ='';//てれてれ                       D
		emoji['e28d'] ='';//青ざめ
		emoji['e28e'] ='';//風邪ひき
		emoji['e28f'] ='';//熱
		emoji['e290'] ='';//横目                           D
		emoji['e291'] ='';//びっくり
		emoji['e292'] ='';//あせり
		emoji['e293'] ='';//楽譜
		emoji['e294'] ='';//にこにこ
		emoji['e295'] ='(>３<)';//チュー２
		emoji['e296'] ='(´３｀)';//チュッ
		emoji['e297'] ='[鼻]';//鼻
		emoji['e298'] ='';//口
		emoji['e299'] ='';//ゴメン／お願い
		emoji['e29a'] ='';//拍手
		emoji['e29b'] ='';//ＯＫ！
		emoji['e29c'] ='';//ブーイング
		emoji['e29d'] ='';//バイバイ
		emoji['e29e'] ='';//ＮＧ
		emoji['e29f'] ='';//ＯＫ！２
		emoji['e2a0'] ='';//平謝り
		emoji['e2a1'] ='';//カップル
		emoji['e2a2'] ='';//バニー
		emoji['e2a3'] ='';//トランペット
		emoji['e2a4'] ='';//ビリヤード
		emoji['e2a5'] ='';//水泳
		emoji['e2a6'] ='';//消防車
		emoji['e2a7'] ='';//救急車
		emoji['e2a8'] ='';//パトカー
		emoji['e2a9'] ='';//ジェットコースター
		emoji['e2aa'] ='';//門松
		emoji['e2ab'] ='';//雛祭り
		emoji['e2ac'] ='[卒業式]';//卒業式
		emoji['e2ad'] ='';//入学式
		emoji['e2ae'] ='';//こいのぼり
		emoji['e2af'] ='';//傘                             D
		emoji['e2b0'] ='';//花嫁
		emoji['e2b1'] ='';//かき氷
		emoji['e2b2'] ='';//線香花火
		emoji['e2b3'] ='';//巻き貝
		emoji['e2b4'] ='[風鈴]';//風鈴
		emoji['e2b5'] ='';//ハロウィン
		emoji['e2b6'] ='';//お月見
		emoji['e2b7'] ='';//サンタ
		emoji['e2b8'] ='';//夜／流れ星                     D
		emoji['e2b9'] ='';//虹
		emoji['e2ba'] ='';//ホテル２
		emoji['e2bb'] ='';//日の出
		emoji['e2bc'] ='';//シルクハット                   D
		emoji['e2bd'] ='';//デパート
		emoji['e2be'] ='[城]';//城（日本）
		emoji['e2bf'] ='[城]';//城（ヨーロッパ）
		emoji['e2c0'] ='';//工場２
		emoji['e2c1'] ='';//フランス国旗
		emoji['e5b5'] ='[ｵｰﾌﾟﾝｳｪｰﾌﾞ]';//オープンウェーブ
		emoji['e5b6'] ='';//ロック確認
		emoji['e5b7'] ='A';//大文字
		emoji['e5b8'] ='a';//小文字
		emoji['e5b9'] ='1';//数字
		emoji['e5ba'] ='＠';//記号
		emoji['e5bb'] ='[可]';//アクセプト
		emoji['e5bc'] ='[ﾁｪｯｸ]';//チェックボックス
		emoji['e5bd'] ='';//エディット                     D
		emoji['e5be'] ='◎';//ラジオボタン
		emoji['e5bf'] ='';//見る
		emoji['e5c0'] ='';//戻る
		emoji['e5c1'] ='';//お気に入り
		emoji['e5c2'] ='';//終了
		emoji['e5c3'] ='';//ホーム
		emoji['e5c4'] ='';//受信箱１
		emoji['e5c5'] ='';//マーク
		emoji['e5c6'] ='';//個人
		emoji['e5c7'] ='';//再読み込み
		emoji['e2c2'] ='';//ドイツ国旗
		emoji['e2c3'] ='';//イタリア国旗
		emoji['e2c4'] ='';//イギリス国旗
		emoji['e2c5'] ='';//中国国旗
		emoji['e2c6'] ='';//中国国旗
		emoji['e2c7'] ='';//白人
		emoji['e2c8'] ='';//中国人
		emoji['e2c9'] ='';//インド人
		emoji['e2ca'] ='';//おじいさん
		emoji['e2cb'] ='';//おばあさん
		emoji['e2cc'] ='';//赤ちゃん
		emoji['e2cd'] ='';//工事現場の人
		emoji['e2ce'] ='';//お姫様
		emoji['e2cf'] ='';//イルカ
		emoji['e2d0'] ='';//ダンス
		emoji['e2d1'] ='';//熱帯魚
		emoji['e2d2'] ='';//げじげじ
		emoji['e2d3'] ='';//象
		emoji['e2d4'] ='';//コアラ
		emoji['e2d5'] ='';//ホルスタイン
		emoji['e2d6'] ='';//ヘビ
		emoji['e2d7'] ='';//鶏
		emoji['e2d8'] ='';//うりぼう
		emoji['e2d9'] ='';//ふたこぶらくだ
		emoji['e2da'] ='[A]';//Ａ型
		emoji['e2db'] ='[B]';//Ｂ型
		emoji['e2dc'] ='[O]';//Ｏ型
		emoji['e2dd'] ='[AB]';//ＡＢ型
		emoji['e2de'] ='';//足跡                           D
		emoji['e2df'] ='';//スニーカー                     D
		emoji['e2e0'] ='';//旗                             D
		emoji['e2e1'] ='';//上向きカーブ矢印               D
		emoji['e2e2'] ='';//下向きカーブ矢印               D
		emoji['e2e3'] ='';//「！？」                       D
		emoji['e2e4'] ='';//「！！」                       D
		emoji['e2e5'] ='';//くるり                         D
		emoji['e2e6'] ='';//メロン
		emoji['e2e7'] ='';//パイナップル
		emoji['e2e8'] ='';//ぶどう
		emoji['e2e9'] ='';//バナナ                         D
		emoji['e2ea'] ='';//とうもろこし
		emoji['e2eb'] ='';//きのこ
		emoji['e2ec'] ='';//栗
		emoji['e2ed'] ='';//桃
		emoji['e2ee'] ='';//やきいも
		emoji['e2ef'] ='';//ピザ
		emoji['e2f0'] ='';//ターキー
		emoji['e2f1'] ='';//七夕笹飾り
		emoji['e2f2'] ='';//トロピカルドリンク
		emoji['e2f3'] ='';//辰
		emoji['e2f4'] ='';//ピアノ
		emoji['e2f5'] ='';//サーフィン
		emoji['e2f6'] ='';//釣り
		emoji['e2f7'] ='';//ボーリング
		emoji['e2f8'] ='[なまはげ]';//なまはげ
		emoji['e2f9'] ='[天狗]';//天狗
		emoji['e2fa'] ='';//パンダ
		emoji['e2fb'] ='';//あかんべー
		emoji['e2fc'] ='';//ぶたの鼻
		emoji['e2fd'] ='';//花
		emoji['e2fe'] ='';//アイスクリーム
		emoji['e2ff'] ='';//ドーナツ
		emoji['e300'] ='';//クッキー
		emoji['e301'] ='';//チョコ
		emoji['e302'] ='';//キャンディ（つつみ）
		emoji['e303'] ='';//キャンディ（ぺろぺろ）
		emoji['e304'] ='(/_＼)';//見ざる
		emoji['e305'] ='(・×・)';//言わざる
		emoji['e306'] ='|(・×・)|';//聞かざる
		emoji['e307'] ='';//火山
		emoji['e308'] ='';//リボンがけのハート
		emoji['e309'] ='[ABC]';//英語「ＡＢＣ」
		emoji['e30a'] ='[ﾌﾟﾘﾝ]';//プリン
		emoji['e30b'] ='[ﾐﾂﾊﾞﾁ]';//ミツバチ
		emoji['e30c'] ='';//テントウムシ
		emoji['e30d'] ='';//蜂蜜ポット
		emoji['e30e'] ='';//青りんご
		emoji['e30f'] ='';//羽のはえたお札
		emoji['e310'] ='';//目がまわる時の記号
		emoji['e311'] ='';//ぷー（かわいく怒）             D
		emoji['e312'] ='';//ぶー（かわいく怒）（ネコ）
		emoji['e313'] ='';//天の川
		emoji['e314'] ='(´З｀)';//チュー（ネコ）
		emoji['e315'] ='';//にこ（ネコ）
		emoji['e316'] ='';//メールする                     D
		emoji['e317'] ='';//泣き笑い（ネコ）
		emoji['e318'] ='';//泣き笑い
		emoji['e319'] ='';//目がハート（ネコ）
		emoji['e31a'] ='';//ほえー（ネコ）
		emoji['e31b'] ='';//ほえー
		emoji['e31c'] ='';//涙ぽろり（ネコ）
		emoji['e31d'] ='';//涙ぽろり（ネコ）
		emoji['e31e'] ='';//きりり（ネコ）
		emoji['e31f'] ='';//ドレス
		emoji['e320'] ='[モヤイ]';//モヤイ像
		emoji['e321'] ='';//駅
		emoji['e322'] ='[花札]';//花札
		emoji['e323'] ='[ｼﾞｮｰｶｰ]';//ジョーカー
		emoji['e324'] ='';//エビフライ
		emoji['e325'] ='';//ｅメールアイコン
		emoji['e326'] ='';//歩く人
		emoji['e327'] ='';//パトカーのランプ
		emoji['e328'] ='[EZ]';//ezmovie
		emoji['e329'] ='';//ドキドキしているハート         D
		emoji['e32a'] ='';//正面向きのひよこ
		emoji['e32b'] ='';//ジーンズ                       D
		emoji['e32c'] ='';//ハートつきメール               D
		emoji['e32d'] ='';//循環矢印                       D
		emoji['e32e'] ='';//左右両方向矢印                 D
		emoji['e32f'] ='';//上下両方向矢印                 D
		emoji['e330'] ='';//荒波                           D
		emoji['e331'] ='';//双葉                           D
		emoji['e332'] ='';//かたつむり                     D
		emoji['e333'] ='';//うっしっし（ネコ）
		emoji['e334'] ='';//うっしっし                     D
		emoji['e335'] ='';//Cメールアイコン
		emoji['e336'] ='';//ハーブ
		emoji['e337'] ='';//グー                           D
		emoji['e338'] ='';//＃                             D
		emoji['e339'] ='';//キャラクター（挙手）     
		emoji['e33a'] ='';//キャラクター（万歳）
		emoji['e33b'] ='';//キャラクター（しょんぼり）
		emoji['e33c'] ='';//キャラクター（かわいく怒る）


 	return(emoji[code]);
}
